spring:
  datasource:
    url: jdbc:h2:mem:testdb # In Memory Mode
    username: sa

  h2:
    console:
      enabled: true # Web Console 사용
      path: /h2-console # Web Console 접속 URL

  jpa:
    hibernate:
      ddl-auto: create