-- App 실행 시 데이터 자동 삽입
INSERT INTO MENU (MENU_NAME, PRICE) VALUES ('떡볶이', 2500);
INSERT INTO MENU (MENU_NAME, PRICE) VALUES ('라볶이', 4000);
INSERT INTO MENU (MENU_NAME, PRICE) VALUES ('순대', 3000);
INSERT INTO MENU (MENU_NAME, PRICE) VALUES ('떡볶이+순대 세트', 5000);